before_install:
 - sudo add-apt-repository ppa:trevorbernard/zeromq -y
 - sudo add-apt-repository ppa:shnatsel/dnscrypt -y
 - sudo apt-get update -y
 - sudo apt-get install libzmq-dev libpgm-dev make build-essential uuid-dev unzip pkg-config libtool automake libsodium -y
 - ./autogen.sh
 - ./configure
 - make
 - sudo make install
install: mvn install --quiet -DskipTests=true -Dgpg.skip=true
language: java

script: mvn test

jdk:
 - openjdk6
 - openjdk7
